### ISSUE TITLE
Add GraSPy to website

### ISSUE THREAD

**Issue by bdpedigo** [neurodata/neurodata.io#143]
Repo
https://github.com/neurodata/graspy

Docs
https://graspy.neurodata.io

PyPI
https://pypi.org/project/graspy/
(not current, but will be soon)

**Comment by loftusa** [comment]
yo i gotchu bruh

**Comment by loftusa** [comment]
(next monday is probably when i gotchu)

**Comment by falkben** [comment]
added to website, but without the links to docs/pypi, since it's underneath the umbrella of graph statistics.
