### ISSUE TITLE
add a "button" for "talk" or "slides" for each tool, as many of them have slides too

### ISSUE THREAD

**Issue by jovo** [neurodata/neurodata.io#24]

**Comment by falkben** [comment]
I think that might have been what the the "press" icon was for in the design.  It's currently enabled.  Just need to add a "press" link for any tool entry that has one.

This is the current icon for "press":
https://github.com/neurodata/neurodata.io/blob/master/source/images/paper.png

**Comment by falkben** [comment]
hey, i think we did this!
