### ISSUE TITLE
add updated slides to ndmg landing page

### ISSUE THREAD

**Issue by falkben** [neurodata/neurodata.io#276]
These are the updated slides.  Let's save them out as html, upload them to the talks repo, and link to them from the ndmg landing page.

https://github.com/neurodata/ndworkshop19/blob/master/ndmg/StructuralConnectomics_ndmg.pptx

**Comment by loftusa** [comment]
Just saw this, there's a PR for linking to these directly. I like the saving as not-`pptx` idea.
Is there an easy way to convert to HTML? Otherwise I might just convert to PDF, since it seems a lot more straightforward.

**Comment by falkben** [comment]
PDF is fine. Can be opened by a browser which is what we want

**Comment by falkben** [comment]
@loftusa I think this is done?

**Comment by loftusa** [comment]
Yep
