### ISSUE TITLE
replace `and others` with full author list.

### ISSUE THREAD

**Issue by MrAE** [neurodata/neurodata.io#310]
@loftusa 

please find and update all instances of `and others` in the posters.bib and talks.bib files to be expanded to the full authors.  See screenshot.

![Screen Shot 2019-10-07 at 11 13 10 AM](https://user-images.githubusercontent.com/6886669/66324499-940ba980-e8f3-11e9-9bf8-4c5ef8a9f611.png)

**Comment by loftusa** [comment]
done - see #312
