### ISSUE TITLE
500 error token

### ISSUE THREAD

**Issue by kyeshmz** [neurodata/neurodata.io#321]
Can't get an api token because of a 500 error.
I don't know where I should put this, so I apologize if this isnt the correct place to flag this.

**Comment by falkben** [comment]
Thanks for reporting.    support@neurodata.io would be good for this but this is also fine.

I did notice some 500 errors.  I believe I have fixed them.  Can you try now? Perhaps just go directly to this link: https://api.boss.neurodata.io/v1/mgmt/token

**Comment by kyeshmz** [comment]
Thank you @falkben for the quick response, I have been able to receive the API token!
