### ISSUE TITLE
url updates

### ISSUE THREAD

**Issue by jovo** [neurodata/neurodata.io#350]
- neurodata.io/graspy --> neurodata.io/graphs
- neurodata.io/sporf --> neurodata.io/forests
- neurodata.io/mgc --> neurodata.io/testing
- neurodata.io/m2g --> neurodata.io/mri

**Comment by tathey1** [comment]
@jovo  https://neurodata.io/mri/ is already a link to the MRI Cloud page, how should this be resolved?
