### ISSUE TITLE
Q: are provenance files not publicly accessible by design or by bug?

### ISSUE THREAD

**Issue by yarikoptic** [neurodata/neurodata.io#352]
In my greedy selfish goal of making more neural data available through datalad from http://datasets.datalad.org/ (and possibly later seeing appropriateness for including or indexing them from https://dandiarchive.org/), I have decided to look into `open-neurodata` bucket (THANK YOU for the project & all the data ;)).  I found that all `/provenance` (and their prehistoric relatives `provenance.json`, which are now removed) are not publicly accessible via http endpoints:

<details>
<summary>datalad ls example, see all the [403] at the end of the line with associated http urls</summary> 

```shell
$> datalad ls -La s3://open-neurodata/kristina15/image/VGluT1_8thA/provenance
Connecting to bucket: open-neurodata
[INFO   ] S3 session: Connecting to the bucket open-neurodata anonymously 
Bucket info:
  Versioning: S3ResponseError: 403 Forbidden
     Website: S3ResponseError: 403 Forbidden
         ACL: S3ResponseError: 403 Forbidden
kristina15/image/VGluT1_8thA/provenance      2019-12-11T19:05:50.000Z 894 ver:M0wNAU.Fcwm5q6e.LVn.xb_2Xdyf6ntA  acl:AccessDenied  http://open-neurodata.s3.amazonaws.com/kristina15/image/VGluT1_8thA/provenance?versionId=M0wNAU.Fcwm5q6e.LVn.xb_2Xdyf6ntA [E: 403]
kristina15/image/VGluT1_8thA/provenance.json 2019-12-11T19:17:19.000Z DeleteMarker
kristina15/image/VGluT1_8thA/provenance.json 2019-12-11T19:15:06.000Z DeleteMarker
kristina15/image/VGluT1_8thA/provenance.json 2019-12-10T17:30:20.000Z 894 ver:16u5oRaZjkjfNkgNs5WlPkaPqBZmKGut  acl:S3ResponseError: 404 Not Found
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>kristina15/image/VGluT1_8thA/provenance.json</Key><RequestId>B19F82F990933470</RequestId><HostId>/anq+TEt28rOZmiSeFSc3g2VnrFXJeF7EH2k89Nby1B3SGvliWTgwqOIgiw+U3FqGDW/uRuXIuY=</HostId></Error>  http://open-neurodata.s3.amazonaws.com/kristina15/im
age/VGluT1_8thA/provenance.json?versionId=16u5oRaZjkjfNkgNs5WlPkaPqBZmKGut [E: 403]

```
</details>

I wondered if that is by design (they contain some sensitive data) or just some bug (so could be addressed).  thank you in advance for the clarification

**Comment by jovo** [comment]
@yarikoptic thanks for the note, sorry i didn't notice this issue earlier.  it is most certainly a bug, 
and we'd wholeheartedly support a PR from your team to fix it if you are willing to do so?

**Comment by yarikoptic** [comment]
Didn't recheck the bucket - were the files made available?

**Comment by PSSF23** [comment]
@yarikoptic we will change the link after finding the very likely re-located file. Thanks.
