### ISSUE TITLE
update agreements with zoom, calendly, and other links

### ISSUE THREAD

**Issue by jovo** [neurodata/neurodata.io#369]
we have this list: https://neurodata.slack.com/files/T0ATB8R52/F014356AGKZ?origin_team=T0ATB8R52
let's put that in agreements.

also, let's make all ND official meetings in my zoom, not pedigo's or some other student's?
this will make it so everyone knows how to get to our meetings

**Comment by jovo** [comment]
(maybe not post my zoom link online because then it can get zoom bombed?)

**Comment by ebridge2** [comment]
That slack-based file is private, right? If so I can just post a link to it (assuming it is perma-linked?) and write that you can reach out to Joshua Vogelstein (with a hyperlink to your email) to get added to the slack workspace, perhaps?

**Comment by jovo** [comment]
let's make agreements comprehensive and self-sufficient, modulo my zoom
room, if you want to link to a slack post and/or private gdocs for the zoom
room link, that is fine.
thanks

On Tue, Jul 7, 2020 at 1:26 PM Eric Bridgeford <notifications@github.com>
wrote:

>
> *      External Email - Use Caution      *
>
>
>
> That slack-based file is private, right? If so I can just post a link to
> it (assuming it is perma-linked?) and write that you can reach out to
> Joshua Vogelstein (with a hyperlink to your email) to get added to the
> slack workspace, perhaps?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fneurodata%2Fneurodata.io%2Fissues%2F369%23issuecomment-655011420&data=02%7C01%7Cjovo%40jhu.edu%7C13f2b69ab30f4366ea0b08d8229adab6%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637297395770612121&sdata=qmFRyHW4Zrht98RmjVWHttGzLoyTF1qpkrspudLXYio%3D&reserved=0>,
> or unsubscribe
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAAKG4QIAQODGOIT2MIBMTLR2NLDNANCNFSM4OS7LHOQ&data=02%7C01%7Cjovo%40jhu.edu%7C13f2b69ab30f4366ea0b08d8229adab6%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637297395770622122&sdata=p7qT1y%2FiWDreb4LCN7LLmdDaBrHBEs%2F4sX9hxxjL%2BHk%3D&reserved=0>
> .
>


-- 
With gratitude,

Joshua T Vogelstein, PhD
neurodata.io | BME@JHU <https://www.bme.jhu.edu/>

Eudaimonia equation
<https://twitter.com/neuro_data/status/1279067902658916352>: dA/dt > 0 >
dJ/dt,
where A = appreciating, J = judging, and t = time
