### ISSUE TITLE
add MSR acknowledgements to the following arxiv/biorxiv articles

### ISSUE THREAD

**Issue by jovo** [neurodata/neurodata.io#386]
please include the following text in each of the below articles, and update them NLT this week.

`Research was partially supported by funding from Microsoft
Research. `

Note: if the manuscript is current in a draft form not ready to be updated, you can simply go to arxiv, download the source, modify it by adding that line, and then re-upload. 

I'm sorry I did not insist on this earlier, I was mistakenly under the impression that it did not matter.

Thank you for acting quickly in this matter which is 100% my fault. 

- [ ] cep: https://www.biorxiv.org/content/10.1101/2020.04.29.068460v2
- [x] @v715 : https://www.biorxiv.org/content/10.1101/701755v2
- [x] @ebridge2 : https://www.biorxiv.org/content/10.1101/802629v4
- [x] @Lawreros : https://www.biorxiv.org/content/10.1101/845065v2
- [x] @ttomita : https://arxiv.org/abs/2007.13843
- [x] @Lawreros : https://arxiv.org/abs/2007.03611 (osf)
- [x] @ebridge2 : https://arxiv.org/abs/2005.11911
- [x] @rflperry : https://arxiv.org/abs/2005.11890
- [x] hayden: https://arxiv.org/abs/2005.10700
- [x] @jdey4 : https://arxiv.org/abs/2004.12908
- [x] @jesusdaniel : https://arxiv.org/abs/1911.02741
- [x] @rflperry:  https://arxiv.org/abs/1909.11799
- [x] tingshan: https://arxiv.org/abs/1909.02688
- [x] @sampan501 : https://arxiv.org/abs/1907.02088
- [x] richard: https://arxiv.org/abs/1907.00325
- [x] @jesusdaniel : https://arxiv.org/abs/1906.03661
- [x] @jesusdaniel : https://arxiv.org/abs/1906.10026
- [ ] @cshen6 : https://arxiv.org/abs/1812.00029
- [x] @j1c : https://osf.io/ek4n3/

**Comment by jovo** [comment]
@j1c added yours too.

**Comment by tliu68** [comment]
@jovo It's done but I can't edit your comment above. I guess I don't have write access?

**Comment by jovo** [comment]
thanks i did it!

**Comment by bdpedigo** [comment]
@hhelm10 dont know if you saw since not tagged

**Comment by hhelm10** [comment]
did not. thank you @bdpedigo
