### ISSUE TITLE
Conflicting mission statements

### ISSUE THREAD

**Issue by m-powell** [neurodata/neurodata.io#411]
Did this:
"Understand and improve animal and machine intelligences worldwide" (mission statement in About)
change to this:
"Understand and improve animal and machine learning worldwide" (landing page)
on purpose?  It looks like it might have been unintentional; otherwise, the two should probably agree.

**Comment by jovo** [comment]
which do you like more, i couldn't decide :)

**Comment by m-powell** [comment]
I think I prefer _intelligences_.  I suspect it's because machine learning has more of an accepted definition as a subset of AI and as a superset of deep learning (which could be exactly what you want).  _Intelligences_ is a bit more flexible and likely could encompass a broader list of things.  I guess I'm suggesting that learning is a subset of intelligence (though this is a claim I've neither thought about nor truly wish to make).  A quick google search reveals the terms _learning_ and _intelligence_ are both used rather loosely, sometimes differentiated by adding the ability to use learned knowledge as a component of intelligence.  If nothing else, _intelligences_ sounds like a bigger deal, and ND is a big deal!
