### ISSUE TITLE
Overlapping text in navigation sidebar in Chrome

### ISSUE THREAD

**Issue by EYezerets** [neurodata/neurodata.io#412]
There are some overlapping buttons/text on the left side near the bottom of the navigation side bar (please see photo) in Chrome when viewing on a laptop.

![image](https://user-images.githubusercontent.com/17932109/98391967-595bcf80-2025-11eb-8df8-6fe17d099722.png)

**Comment by Lawreros** [comment]
Is there a specific page where this occurs?

**Comment by EYezerets** [comment]
It occurs on all pages for me.

**Comment by PSSF23** [comment]
Same issue confirmed on other browsers (Safari, Firefox) with window sizes that are too short, particularly evident when resizing the browser window. When the texts are overlapped, the main navigation menu (ABOUT, BLOG, JOIN...) is not reachable.
