### ISSUE TITLE
Cannot reach bottom navigation menu in mobile sites

### ISSUE THREAD

**Issue by PSSF23** [neurodata/neurodata.io#422]
When accessing the website on mobile devices, the bottom navigation menu (EMAIL, TWITTER, MEET...) is not visible. Adding the items to the main navigation menu (DATA, CODE, PUBS...) might resolve this issue.

**Comment by Lawreros** [comment]
fixed in 3efe6adfe733fd8f2eed2ab9133bd2c97b1cca5c
