### ISSUE TITLE
pubs

### ISSUE THREAD

**Issue by jovo** [neurodata/neurodata.io#439]
- [ ] some of @ebridge2 articles are there multiple times.
- [x] in pre-prints, some say 'none' rather than 'arxiv'
- [x] UF does not have a link to arXiv.
- [ ] some pubs list more details (eg, issue, page numbers), but they should all only include: all authors, title, journal, year.

**Comment by rflperry** [comment]
Nonparametric MANOVA via Independence Testing (https://arxiv.org/abs/1910.08883) should be listed

**Comment by m-powell** [comment]
I see one missing pre-print:
M. Powell, A. Koenecke, J. B. Byrd, A. Nishimura, M. F. Konig, R. Xiong, S. Mahmood, V. Mucaj, C. Bettegowda, L. Rose, S. Tamang, A. Sacarny, B. Caffo, S. Athey, E. A. Stuart, and J. T. Vogelstein.  “A How-to Guide for Conducting Retrospective Analyses: Example COVID-19 Study.” OSF Preprints, 2020.
link: https://osf.io/3drch/

**Comment by sampan501** [comment]
- (20) mgcpy should be updated to hyppo: https://arxiv.org/abs/1907.02088
- (28) characteristic kernel: https://arxiv.org/abs/1812.00029

**Comment by Lawreros** [comment]
This will be taken care of with the update to the website connecting it to the cv repository
