### ISSUE TITLE
Question about Overleaf papers

### ISSUE THREAD

**Issue by tathey1** [neurodata/neurodata.io#446]
Standard process of writing papers in the lab is to make jovo the owner of the [overleaf](https://github.com/neurodata/neurodata.io/blob/deploy/content/about/agreements.md). This makes it no longer possible for me to share the overleaf with others. 
- Is this a typical problem?
- What's the standard solution? message jovo asking for link or what?

**Comment by rflperry** [comment]
I've had to ask jovo to add people by email multiple times before.
