### ISSUE TITLE
i wrote a new paragraph about my research interests

### ISSUE THREAD

**Issue by jovo** [neurodata/neurodata.io#450]
Joshua Vogelstein, Ph.D., Assistant Professor of Biomedical Engineering (WSE). Dr. Vogelstein’s research is devoted to developing and applying biomedical data science theory and methods. This typically includes dealing with high-dimensional, nonlinear, structured data with low-sample sizes.  Dr. Vogelstein has developed the leading machine learning and artificial intelligence (ML/AI) methods and software tools for managing large imaging data, as well as the state-of-the-art multivariate hypothesis testing, clustering, and classification techniques.  His work primarily focuses on brain data, including brain networks, anatomy, physiology, and behavior/cognition.  Recently his lab has also focused on COVID-19, including real-world evidence with causal inference, as well as addressing current bottlenecks in AI development, such as lifelong learning. Dr. Vogelstein is passionate about democratizing science at all levels, and is deeply engaged in education and outreach, as well as research.

prob should add to my page.

**Comment by Lawreros** [comment]
Currently your page uses the text from your jovo.me page, which is in the first person. Do you want to switch to third person?

**Comment by jovo** [comment]
i guess stay in 1st person, sorry.

On Tue, Mar 30, 2021 at 4:22 PM Ross Lawrence ***@***.***>
wrote:

> Currently your page uses the text from your jovo.me page, which is in the
> first person. Do you want to switch to third person?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>


-- 
With gratitude,

Joshua T Vogelstein, PhD
neurodata.io | BME@JHU <https://www.bme.jhu.edu/> | dA/dt > 0 > dJ/dt
<https://twitter.com/neuro_data/status/1279067902658916352>
where A = appreciating, J = judging, and t = time.
How can I do better? <https://forms.gle/iEad8byD89eTPdYx6>
