### ISSUE TITLE
IMO talks and posters should be in pubs, not other

### ISSUE THREAD

**Issue by bdpedigo** [neurodata/neurodata.io#456]
thoughts? @jovo @Lawreros 

currently talks are here https://neurodata.io/other/talks/

I think they should be with everything here https://neurodata.io/research/

**Comment by jovo** [comment]
i think that makes sense.  we'd want to rename the sidebar to be 'research' rather than 'pubs'.
@bdpedigo is that something you are willing to do?
if not, let's assign it to one of the new undergrads...

**Comment by bdpedigo** [comment]
not something I want to commit to ATM.
