### ISSUE TITLE
update 'join us' page

### ISSUE THREAD

**Issue by jovo** [neurodata/neurodata.io#480]

**Comment by asaadeldin11** [comment]
should the update essentially reflect what's currently written in your automated email response?

**Comment by jovo** [comment]
good idea!

**Comment by Lawreros** [comment]
@asaadeldin11 Can you take care of this? The file is here (https://github.com/neurodata/neurodata.io/blob/deploy/content/pages/join.html)

**Comment by asaadeldin11** [comment]
yeah i can take care of this

**Comment by asaadeldin11** [comment]
so we want to remove all of the email communication stuff?
@jovo
