### ISSUE TITLE
Publication Sign-off

### ISSUE THREAD

**Issue by Lawreros** [neurodata/neurodata.io#489]

**Comment by m-powell** [comment]
I checked my pubs.  All are correct and show up on the correct tab on the website.

**Comment by vikramc1** [comment]
I had a missing publication and made a PR to add it here: https://github.com/neurodata/neurodata.io/pull/491

**Comment by tathey1** [comment]
changes for me are pending:
- PR was merged: https://github.com/neurodata/neurodata.io/pull/488
- One PR under review: https://github.com/neurodata/neurodata.io/pull/493
- another PR under review: https://github.com/neurodata/neurodata.io/pull/496

**Comment by meghana-madhyastha** [comment]
I made a PR to add a recent conference publication #495 and it is pending review.

**Comment by tliu68** [comment]
I opened [PR #493](https://github.com/neurodata/neurodata.io/pull/493) to update a preprint. It's under review now.
