### ISSUE TITLE
home pages for neurodata packages

### ISSUE THREAD

**Issue by asaadeldin11** [neurodata/neurodata.io#539]
All neurodata packages should have a home page, that then links to the docs the page. See [graph-tool's homepage](https://graph-tool.skewed.de/) for reference.

**Comment by PSSF23** [comment]
Counter-argument: jovo's comment in #459 means to reduce maintenance, but a whole doc page is much more complicated than a `yaml` file linked with internal `bib` references. I can create a `neurodata.io/PACKAGE_NAME` page in minutes but not the whole `netlify`/`sphinx` implementations.

**Comment by asaadeldin11** [comment]
To clarify, Jovo wants that each package to host their own homepage, independent from neurodata.io. 
Also, shouldn't the code page be more so for packages/libraries specifically. I'm not sure that github pages including code for a specific paper belong on this page, because I imagine it will get very long/messy.

**Comment by PSSF23** [comment]
Current `neurodata.io/PACKAGE_NAME` pages have nothing to do with GitHub pages, and they can refer to entries in `pubs.bib` directly. But I see what your plan. That will take some weeks, and all references in cv/repos need to be updated.

**Comment by asaadeldin11** [comment]
i mean, for example, rf-dn-paper isn't really a package, it's a github page to host code for a paper. So I'm not sure if it's appropriate to be under the featured section of the code page. I don't have an issue with it's `neurodata.io/PACKAGE_NAME` existing, but I don't think it should be listed on the code page. Do you agree?

**Comment by PSSF23** [comment]
Jovo asked me to add it there. Notebooks/cloud are not packages, either.

**Comment by PSSF23** [comment]
Here are some merits of current implementation:

- Once the `bib` entry is updated, it's synced everywhere on the website.
- Links to slides & lab pages are directly accessible.
- Very easy start for new projects like DF/DN. More docs/slides/pubs can be added later.
- Even if the links are changed to doc pages, the `yaml` files will still generate the URLs and people need to maintain them anyway.

**Comment by Lawreros** [comment]
I'm with Hao on this one, giving each of the entries their own homepage will quickly result in the information there being out of date with the package. It's way easier to just have the READ.me's of the github repositories be up to date and just link to them

**Comment by jovo** [comment]
Happy to discuss, my basic thought is that we want webpages x.neurodata.io, where 'x' is each 'thingy' that has code associated with it.  readme's quickly get out of date and redundant with webpages.  i would like github to *only* have content, but not be a website that is ever worth going to unless they literally want to see our code.  in other words, all readme's would simply say, go to x.neurodata.io for information, and have a bunch of badges.

We could have 2 'groups' of project pages, one for 'big ones' with an actual package, and one for little ones with just jupyter notebooks, etc.

So, i guess I do think anything we have with any code should be listed on code page, and maybe 3 sections:

1. packages
2. projects with code
3. commits/contributions to open source repo's maintained outside of neurodata

Thoughts?

**Comment by jshinm** [comment]
@PSSF23 @asaadeldin11 @Lawreros -- can we close this issue now?

**Comment by jshinm** [comment]
Suggestion reflects current status of the code page
