### ISSUE TITLE
update wikipedia

### ISSUE THREAD

**Issue by jovo** [neurodata/neurodata.io#556]
1. open connectome project
2. biomedical data science
https://en.wikipedia.org/wiki/User_talk:Joshuav#Biomedical_data_science_moved_to_draftspace

@tathey1 may have more information.  let's get this done this week please.

**Comment by jshinm** [comment]
this is a continuation of issue #494

- the issue raised for OCP could be resolved by adding cross-refs as required external sources
- BDS is practically has not been written, will follow up with jovo on planning

**Comment by jshinm** [comment]
BDS is published and is actively being updated
https://en.wikipedia.org/wiki/Biomedical_data_science
