### ISSUE TITLE
Read the Papers from Jovo + Pratik + Rahul + Ashwin Meeting

### ISSUE THREAD

**Issue by Laknath1996** [neurodata/neurodata.io#565]
The following are the papers that were suggested during the meeting: 

1. Deep Reference Priors: What is the best way to pretrain a model? (this paper is not in arxiv yet, and therefore was slacked to Jovo)
2. A theory of learning from different domains ([paper](https://www.alexkulesza.com/pubs/adapt_mlj10.pdf))
3. A Notion of Task Relatedness Yielding Provable Multiple-Task Learning Guarantees ([paper](http://people.ee.duke.edu/~lcarin/reba_pap_jver.pdf))
4. Model Zoo: A Growing “Brain” That Learns Continually ([paper](https://arxiv.org/pdf/2106.03027.pdf))

Tasks:

- Read theorem 3 from the "A theory of learning from different domains"  ([paper](https://www.alexkulesza.com/pubs/adapt_mlj10.pdf))
- Check the equation 9 in "Embracing the Disharmony in Medical Imaging: A Simple and Effective Framework for Domain Adaptation" ([paper](https://arxiv.org/pdf/2103.12857.pdf))

@jshinm Can you kindly assign Jovo to this issue? thanks! :)

**Comment by jshinm** [comment]
@Laknath1996 how's the progress on this issue?

**Comment by jshinm** [comment]
closed as it's over due
