### ISSUE TITLE
make the aspect ratio for my slides right for my monitor

### ISSUE THREAD

**Issue by jovo** [neurodata/neurodata.io#567]
i have a 5k LG monitor. LG UltraFine Display 27-inch 2880 x 5120
need to make a new file `slides_style_i.css`
for the correct aspect ratio.

**Comment by jshinm** [comment]
@jovo I assumed your wide screen is stretching the slide contents, so I added a couple of [additional properties](https://github.com/neurodata/talks/commit/b46a51255253f0e1279d59d3283e1d04c7c153da#diff-774fbc83d50c7575012d4a53e54c9cfb577c6acf901b0430b77458cbbcd14954R278-R281) to `.remark-slide-content` to fit inner div to its contents. Did it do anything for you?

https://neurodata.io/talks/emerson21.html#1

**Comment by jovo** [comment]
no. do you have access to a widescreen monitor?
the currect aspect ratio is for non-widescreen.
on widescreen, there are gray bars on the sides.

**Comment by jshinm** [comment]
Thank you, this is helpful. I will get this corrected

**Comment by jshinm** [comment]
https://github.com/neurodata/talks/commit/2657ac153e9de876b1c9f8deecd0378e01a3dfcb
