### ISSUE TITLE
Letter for NIH (Research Progress Report, due 1/15)

### ISSUE THREAD

**Issue by javierhow** [neurodata/neurodata.io#574]
Hello!

The research progress report for my NIH grant is due January 15 2022. I wrote a letter (https://docs.google.com/document/d/1Mteug28nPMYGPCumRl_2Ms_pp1rKTmEeHjJ8jQkvooQ/edit?usp=sharing) and just need Jovo to 1) look it over, 2) sign, and 3) list some grants in the assigned space (so the NIH knows the lab has money to support my research). Prompt is at the top.

Thanks!

**Comment by jshinm** [comment]
Closed as it's past due
