### ISSUE TITLE
Biosketch for NSF (due 1/11/22)

### ISSUE THREAD

**Issue by javierhow** [neurodata/neurodata.io#575]
I need Jovo's NSF-style biosketch.

> 
5. Biographical Sketches (3-page limit per person): Biographical sketches are required for the PI, any co-PIs, and each of the participating Senior Personnel listed in the Project Description. All biographical sketches submitted in response to this solicitation are expected to follow the NSF-approved format in accordance with the policy found at https://www.nsf.gov/bfa/dias/policy/biosketch.jsp. Note that this policy states that effective October 4, 2021, the page limitation for biographical sketches will be increased to 3 pages.

**Comment by jshinm** [comment]
Closed as it's past due
