### ISSUE TITLE
add normal titles back to team page

### ISSUE THREAD

**Issue by bdpedigo** [neurodata/neurodata.io#599]
when i look at a lab webpage it is actually very helpful to be able to see what roles everyone in the lab is in

the new lab titles on the about page obfuscate that

i would be pro showing both titles somehow, if that is easy to do

**Comment by jshinm** [comment]
@jovo I think we may need your input on this?

**Comment by jovo** [comment]
that is easy to do. show both.

i also wonder though: what is the value of knowing that somebody is a postdoc rather than a phd student?

also, is the current importance of that something that we want to promote as a community, or would we rather promote flattening hierarchies?

**Comment by jshinm** [comment]
@bdpedigo just to get your attention :)

**Comment by bdpedigo** [comment]
> that is easy to do. show both.
> 
> i also wonder though: what is the value of knowing that somebody is a postdoc rather than a phd student?
> 
> also, is the current importance of that something that we want to promote as a community, or would we rather promote flattening hierarchies?

i think for people who potentially want to work in the lab it can be helpful to see does the lab take post-docs? undergrads? and just seeing what the makeup of the lab is in that regard. i can ask around the lab and see if anyone agrees/disagrees with me

**Comment by m-powell** [comment]
I vote show both.  Something official and something unofficial.  It shows both helpful information about lab makeup and a bit of personality...on a page whose audience isn't us.

**Comment by jovo** [comment]
i vote: people write whatever they want.  i support both, or one, or the other.  that said, if the lab strongly feels like we should do one or the other or both, i'm happy to support whatever you all believe is best.

**Comment by jshinm** [comment]
as per plurality decision, we will display academic title in parenthesis in addition to current fun title
