### ISSUE TITLE
outdated/incomplete lab responsibiliities

### ISSUE THREAD

**Issue by tathey1** [neurodata/neurodata.io#603]
some things to consider for [this](https://neurodata.io/other/community_jobs/) page:
- some members are no longer in the lab (i think?)
- no high inquisitor (do we want one?)
- monthly hike is incomplete
- should we add Jong

**Comment by jshinm** [comment]
I can keep the member page up-to-date :)
I think I could join the lab website management + aws management teams?

**Comment by jovo** [comment]
@jshinm please fix
