### ISSUE TITLE
grow-ext-html-min issue (website/netlify won't build)

### ISSUE THREAD

**Issue by Lawreros** [neurodata/neurodata.io#606]
@jshinm 
Issue in `grow` generation of the website using `extensions.txt`:
`git+git://` no longer supported due to security reasons ([here](https://github.blog/2021-09-01-improving-git-protocol-security-github/)).
I'm working on a fix at the moment.

**Comment by jshinm** [comment]
@Lawreros Jovo actually brought this up to me a few weeks ago, and I made a change to fix it [here](https://github.com/neurodata/neurodata.io/pull/592/commits/b04fa6298fbe467af0bd731b6af5d93c78f7d084). It seems working fine now for our PR. Would this help? #592 is the PR

**Comment by Lawreros** [comment]
Ah, okay, didn't see that. If it works for netlify, it should work for our website. If the PR works, please close this issue
