### ISSUE TITLE
add a README for how to add content to bib files, remove any unnecessary bibs

### ISSUE THREAD

**Issue by bdpedigo** [neurodata/neurodata.io#621]

**Comment by jshinm** [comment]
@Lawreros is it okay if we work on this and clean up files? I know you are implementing some changes. I wonder if you are finished

**Comment by Lawreros** [comment]
In the existing README file for neurodata.io there is an explanation on how to add content to the bib files. Does that need to be fleshed out more?

**Comment by jshinm** [comment]
@Lawreros agreed! @bdpedigo I think Ross is referring to [this](https://github.com/neurodata/neurodata.io#team-member-addition-info) section of the readme. @Lawreros nonetheless, could we reorganize bib files (i.e., deleting bibs that are not used for the website)? Or do you think it's better off left as it is

**Comment by bdpedigo** [comment]
my bad, i had not seen that section of the readme.

related question - is abspos the same as inproceedings? I know a lot of posters are the latter right now

**Comment by jshinm** [comment]
I just now saw your comment, and no worries @bdpedigo 😄. As far as the website is concerned (to the best of my knowledge), it reads from the `keyword` attribute to determine whether it's a poster or not. So if I were to make an entry for a poster, I would just get the bibtex of my poster (or copy off other refs as a template and update the info) and make sure I have the right keywords. And as you correctly identified, most of the posters are inproceedings (though some are not, e.g., articles). I hope this helps!

**Comment by Lawreros** [comment]
`abspos` corresponds to the "Abstracts/Posters" section on his webpage [here](https://neurodata.io/about/jovo/). I did this based off of what were already in this section in his CV when I was put in charge of cleaning things up, so I don't have a great definition of it.
