### ISSUE TITLE
build image is now deprecated

### ISSUE THREAD

**Issue by tathey1** [neurodata/neurodata.io#676]
it appears that the build image we use is no longer supported, so new PR's are failing e.g. https://github.com/neurodata/neurodata.io/pull/675

I think we simply need to change to a new image: https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239

**Comment by jshinm** [comment]
Thank you so much for not merging the PR, @tathey1 ❤️! I've briefly switched to the new image, but it seems like I'll have to update the dependencies. I will troubleshoot this afternoon and get it done by today!
