### ISSUE TITLE
02/24/2023: update webpage to fix typos, please prioritize for next week

### ISSUE THREAD

**Issue by jovo** [neurodata/neurodata.io#727]
The current paragraph is this:

```Joshua Vogelstein, PhD, is an Associate Professor in the Department of [Biomedical Engineering](http://www.bme.jhu.edu/) at [Johns Hopkins University](https://www.jhu.edu/), with joint appointments in Applied Mathematics and Statistics, Computer Science, Electrical and Computer Engineering, Neuroscience, and Biostatistics. His research focuses primarily on the intersection of natural and artificial intelligence. Our group develops and applies high-dimensional nonlinear machine learning methods to biomedical data science challenges. We have published over 100 papers in prominent scientific and engineering journals and conferences including Nature, Science, PNAS, Neurips, and JMLR, with over 10,000 citations and an h-index over 40. We received funding from the Transformative Research Award from NIH, the NSF CAREER award, Microsoft Research, and many other government, for-profit and nonprofit organizations. He has advised over 60 trainees, and taught about 200 students in his eight years as faculty. In addition to his academic work, he co-founded Global Domain Partners, a quantitative hedge fund that was acquired by Mosaic Investment Partners in 2012, and software startup Gigantum, which was acquired by nVidia in early 2022.```

But that has some weird typos in it.  Please change it to this:

```Joshua Vogelstein, PhD, is an Associate Professor in the Department of [Biomedical Engineering](http://www.bme.jhu.edu/) at [Johns Hopkins University](https://www.jhu.edu/), with joint appointments in Applied Mathematics and Statistics, Computer Science, Electrical and Computer Engineering, Neuroscience, and Biostatistics. His research focuses primarily on the intersection of natural and artificial intelligence. His group develops and applies high-dimensional nonlinear machine learning methods to biomedical data science challenges. They have published over 100 papers in prominent scientific and engineering journals and conferences including Nature, Science, PNAS, Neurips, and JMLR, with over 11,000 citations and an h-index over 40. They have received funding from the Transformative Research Award from NIH, the NSF CAREER award, Microsoft Research, and many other government, for-profit and nonprofit organizations. He has advised over 60 trainees, and taught about 200 students in his eight years as faculty. In addition to his academic work, he co-founded Global Domain Partners, a quantitative hedge fund that was acquired by Mosaic Investment Partners in 2012, and software startup Gigantum, which was acquired by nVidia in early 2022.  He is currently also serving as Chief Intelligence Officer for [Sensie](https://joinsensie.com/) a startup devoted to unblocking intelligence to optimize our collective wellness. He lives in the Chesapeake Bay Watershed with his beloved wife and three children.```

**Comment by jovo** [comment]
this did not happen.  at least the last 2 sentences are not live. please update urgently.

**Comment by jshinm** [comment]
@jovo Oh no! I'm sorry, something must have happen in backend. I'll investigate right now

**Comment by jshinm** [comment]
There had been an issue with site building from aws. The path for pdflatex to which it was reading files from was incorrect. The hotfix has been implemented.

Now seems to be a good time to find a way to monitor aws build status (e.g., badge) so in the future we know if the website actually built or not. The relevant issue had been created for this in the past (#687)
