### ISSUE TITLE
02/24/2023: center headings on overleaf

### ISSUE THREAD

**Issue by jovo** [neurodata/neurodata.io#728]
@jshinm i'd like the headings centered in this document:
https://www.overleaf.com/3562373141zbywjvjgghzs

i spent about an hour trying to figure it out, and so far, have failed.
i'm confident there is an easy fix, but i'm not that good at latex.
it is not urgent, and i would like your help when you have about an hour to spare.

**Comment by jshinm** [comment]
Centered \section, \subsection, \subsubsection using `titlesec` package
