### ISSUE TITLE
02/28/2023: some misc activities

### ISSUE THREAD

**Issue by jovo** [neurodata/neurodata.io#732]
1. there is a PR for this repo called `sickness-schedule', please merge and post the diff in #core so everybody sees it (this week)
2. in https://www.overleaf.com/3562373141zbywjvjgghzs, can you do the following:
   - make it so that enumerated/numbered lists are not negative indented, they should just be at the normal left side of a column
   - make definitions (defined by Def environment) not indented
   - make the first paragraph not indented
   - make svg's work (i have one in there currently that is not working)

 please prioritize 2 for the next time you have a 5 hr window of non-software.

**Comment by jovo** [comment]
actually, regarding 2 above, i notice that i am confused.  we have a neurodata template that you have been maintaining: https://www.overleaf.com/10197424qzprmvhnhjsn, but it has compile errors. 

and we also link to something else in https://neurodata.io/about/agreements/, namely https://www.overleaf.com/9118371155tpfdvbbbrybp

so, i switched it, now lists are ok, def's are ok, indents are ok.
the only thing that fails is svg. 
so, please fix that when you get a chance.

**Comment by jshinm** [comment]
- [x] Merge `sickness-schedule` and post the update in slack
- [x] Investigate and allow svg to be rendered: https://www.overleaf.com/3562373141zbywjvjgghzs
    - Jovo might have fixed this
- [x] Fix compile error: https://www.overleaf.com/10197424qzprmvhnhjsn
    - Eric's table throwing errors (possibly not compatible with NDD pre-amble packages)
    - Commented out the table temporarily
