### ISSUE TITLE
03/20/2023: Update funding section of the website

### ISSUE THREAD

**Issue by jovo** [neurodata/neurodata.io#751]
see email for details

EDIT - update funding section according to current funding status detailed by Lisa

**Comment by jshinm** [comment]
- Sent emails to Lisa for active funding list
- Uploaded pdf format of the complete lab member list to HHMI
- Prepped and shared word doc for Heather

**Comment by jshinm** [comment]
The deadline is 3/21/2023

**Comment by jshinm** [comment]
Sent the most up to date biosketch to Heather as a reference
