### ISSUE TITLE
a page for clarity stuff, like synaptomes page

### ISSUE THREAD

**Issue by jovo** [neurodata/neurodata.io#79]
not sure exactly what it is called, (maybe mesoscale or CLARITRONS) but it includes:

Data
- deisseroth16

Pubs:
- kwame1 & kwame2
- recent review article from karl d (citation #12 in OCPaper on arxiv)
- tomer paper from OCPaper

tools
- ndpush
- ndpull
- ndweb
- ndreg
- ndviz

People
- includes kwame, ailey, and karl?

**Comment by falkben** [comment]
@loftusa -- i think a few papers are missing from above (tomer and review article from karl)?
