### ISSUE TITLE
MGC docs link broken

### ISSUE THREAD

**Issue by falkben** [neurodata/neurodata.io#80]
https://github.com/neurodata/neurodata.io/blob/3036e8d2d99b42621f77de648bedb34099ea9421/content/tools/mgc.yaml#L8

Currently points to https://neurodata-papers.github.io/MGC/ which does not work

Is there a better doc link to use or should I remove?

**Comment by ebridge2** [comment]
https://github.com/neurodata/mgc

**Comment by falkben** [comment]
Okay, we already have link to that, so I'll remove the specific link to the broken docs.
