### ISSUE TITLE
publications format

### ISSUE THREAD

**Issue by jovo** [neurodata/neurodata.io#84]
i think it'd be nicer if they conformed to a more "expected" format, such as

F Last, F Last, et al. Title. <it>Venue (journal/conf)</it> issue/month/pg, year. <link to pdf> <link to journal page> <link to code when relevant>

**Comment by falkben** [comment]
I think this necessitates me changing the data layer to use bibtex, after which, we can use whichever output format we want.  Finding it too hard to enter it all in manually.  And all the pubs currently only have year, title, name, and link to article, so to update them all would be unpleasant.  Using a bibtext source shouldn't be too difficult.

**Comment by jovo** [comment]
ok great! as noted, it is not urgent, but would be nice.

**Comment by falkben** [comment]
https://github.com/neurodata/neurodata.io/commit/83c4f2bf83a4e714b41cf206f58ade4da6144552 closes
