### ISSUE TITLE
bibtex formatting

### ISSUE THREAD

**Issue by jovo** [neurodata/neurodata.io#92]
can you:

1. make the text not bold (it seems bold)
2. remove the word "In", it seems unnecessary
3. for arxiv stuff, simplify: " arXiv preprint arXiv:1710.09859" to merely "arXiv:1710.09859"
4. for bioRxiv, complexify: "bioRxiv" to "bioRxiv:289504" (the number is the last digits of the url)

**Comment by falkben** [comment]
for not bold, there are pubs with different formatting right now.  

1. There's pubs listed on [projects](https://neurodata.io/project/synaptomes/) and on each individual [data/project](https://neurodata.io/data/bloss2016/) page.  
1. There's pubs listed on *the* [data](https://neurodata.io/data/) page.

Do want them _both_ to be *not* bold?  Or just one or the other?
